### PR TITLE
feat: [WIP] `@pixi/react` v8

### PR DESCRIPTION
**Pull request by trezy**
##### Description of change
This is a complete rewrite of `@pixi/react`. It leverages reflection and type inference to provide a new React pragma, allowing usage of all Pixi.js components via JSX within React applications.

A nice side effect is that this new version _should_ be backward-compatible.

This PR supersedes @Zyie's work on #483, since we're now rewriting the library from the ground up.

Fixes: #476 

##### Pre-Merge Checklist
- [ ] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [ ] Tests passed (`npm run test`)
- [ ] Codemods added

### CODE REVIEW

**Comment by lunarraid** [comment]
What's the reasoning behind a complete rewrite rather than bumping the signatures from the prior version?

**Comment by sergioisidoro** [comment]
I'm also curious to know the rational behind a full re-write. The current version already has an implementation of a react reconciler, which seems to work with react fiber, with what looks like a well though out reconciliation strategy and event priorities. Could we perhaps get some more insight behind the factors that you considered? 

There is a lot of code that is being removed, and with it a lot of accumulated knowledge and "chesterton fences".

**Comment by utenma** [comment]
maybe?

> It leverages reflection and type inference to provide a new React pragma

> A nice side effect is that this new version should be backward-compatible.

**Comment by lunarraid** [comment]
Definitely not backwards-compatible.

**Comment by YVeselovskyi** [comment]
hello :) 
is there any info when v8 support will be added?

thanks!

**Comment by trezy** [comment]
I've closed this PR since I've moved development to the `dev` branch for now. I also created a new issue (#493) to track progress on the new version of the library. That issue also provides context around the decision to rewrite the library from scratch, as well as other changes being made.

**Pull request closed without merging**
