### PR TITLE
[WIP] Pixi v8 update

### PR DESCRIPTION
**Pull request by Zyie**

### CODE REVIEW

**Comment by pie6k** [comment]
Looks like amazing work! Thank you!

**Comment by rnike** [comment]
Thanks a lot for the work, we look forward to this update.

**Comment by CaptainStiggz** [comment]
Thanks for this, can't wait!

**Comment by KashubaK** [comment]
Really looking forward to this, thank you for your efforts!

**Comment by alexwine36** [comment]
Also, really looking forward to this!

**Comment by omasri-tb** [comment]
Thanks for working on this, can't wait!

**Comment by vhaine-tb** [comment]
Really looking forward to this!

**Comment by feliperodrigues-tb** [comment]
Really looking forward to this!

**Comment by bruno-tb** [comment]
I can't wait for it!

**Comment by Chediak** [comment]
Can't wait

**Comment by MKonopelski** [comment]
This would help us a lot!! Thanks.

**Comment by ricardosalvimachida** [comment]
Really looking foward do this

**Pull request closed without merging**
